#!/usr/bin/env bash
#  _____ _           ____                     _   _ _        _       
# |_   _| |__   ___ / ___| __ _ ___ ___ _   _| \ | (_)_ __  (_) __ _ 
#   | | | '_ \ / _ \ |  _ / _` / __/ __| | | |  \| | | '_ \ | |/ _` |
#   | | | | | |  __/ |_| | (_| \__ \__ \ |_| | |\  | | | | || | (_| |
#   |_| |_| |_|\___|\____|\__,_|___/___/\__, |_| \_|_|_| |_|/ |\__,_|
#                                       |___/             |__/       
#   Spawned: Thu Jan 19 2023 - 04:14
#  Last Mod: Wed Feb 01 2023 - 06:59
#  Config:
#  Depends:
#  Note:
#
hc() {
    herbstclient "$@"
}
hc emit_hook reload

# Env Vars
TERMINAL=alacritty

# Auto-Start
#./home/thegassyninja/.config/herbstluftwm/panel.sh
~/.config/polybar/poly-launch.sh
#~/.fehbg &
picom --config ~/.config/picom.conf --animations --animation-for-open-window fly-in &
easyeffects --gapplication-service &
xset s off -dpms
mpd
playerctld &
mpDris2 &
#sleep 5 ; back4.sh 0.010 ~/Downloads/space2.gif


#
hc keyunbind --all
source $HOME/.config/herbstluftwm/keys

source $HOME/.config/herbstluftwm/theme

source $HOME/.config/herbstluftwm/rules

hc unlock
hc detect_monitors

ps -aux | grep back4.sh | kill $(awk '{print $2}')
sleep 3 ; back4.sh 0.010 ~/Downloads/space2.gif

# find the panel
#panel=~/.config/herbstluftwm/panel.sh
#[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
#for monitor in $(hc list_monitors | cut -d: -f1) ; do
#   # start it on each monitor
#    "$panel" "$monitor" &
#done
