#!/usr/bin/env sh
# _____ _           ____                     _   _ _        _       
#|_   _| |__   ___ / ___| __ _ ___ ___ _   _| \ | (_)_ __  (_) __ _ 
#  | | | '_ \ / _ \ |  _ / _` / __/ __| | | |  \| | | '_ \ | |/ _` |
#  | | | | | |  __/ |_| | (_| \__ \__ \ |_| | |\  | | | | || | (_| |
#  |_| |_| |_|\___|\____|\__,_|___/___/\__, |_| \_|_|_| |_|/ |\__,_|
#                                      |___/             |__/       
#  Spawned: Wed Jan 25 2023 - 07:47
#  Last Mod: Thu Jan 26 2023 - 00:11
#  Script:
#  Depends:
#  Note:
LAST=$(cat ~/.local/tmp/mpc-current.txt)
ARTIST=$(mpc current | cut -d "-" -f 1 | sed 's/^[ \t]*//;s/[ \t]*$//')
TITLE=$(mpc current | cut -d "-" -f 2 | sed 's/^[ \t]*//;s/[ \t]*$//')

mpc_update() {
	echo $(mpc current) > $HOME/.local/tmp/mpc-current.txt	
	 songLyrics "$ARTIST" "$TITLE" | grep -v "(ht" > ~/.local/tmp/lyrics.txt
	
}

	if [[ $(mpc current) = $LAST ]]; then
		echo "$ARTIST <--> $TITLE" ; cat ~/.local/tmp/lyrics.txt
	else
		mpc_update 

	fi









#echo "$ARTIST - $TITLE" && songLyrics "$ARTIST" "$TITLE" | grep -v "(ht"
